# Generated by Django 3.1.5 on 2021-01-06 14:59

from django.db import migrations, models
import documentScanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageScanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ImageFile', models.FileField(upload_to=documentScanner.models.upload_to)),
            ],
        ),
    ]
