# Generated by Django 3.1.5 on 2021-01-08 12:15

from django.db import migrations, models
import documentScanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentScanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagescanner',
            name='ImageFile',
            field=models.ImageField(upload_to=documentScanner.models.upload_to),
        ),
    ]
