# Generated by Django 3.1.5 on 2021-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentScanner', '0002_auto_20210108_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagescanner',
            name='ImageFile',
            field=models.ImageField(upload_to='newimages'),
        ),
    ]
